title: Established New Governance
description: Cayman is a clean, responsive theme for GitHub Pages.
url: https://eintnohick.github.io/established-new-governance
google_analytics: 
include: ['_pages']